#!/usr/bin/python3
# Given a .json file produced by ld-process-vbi, extract data from the VBI
# information in useful formats.

import argparse
import json
import re
import sys

def getbcd(bcd):
    """Read a BCD-encoded number.
    Raises ValueError if any of the digits aren't valid BCD."""
    if bcd == 0:
        return 0
    else:
        digit = bcd & 0xF
        if digit > 9:
            raise ValueError("Non-decimal BCD digit")
        return (10 * getbcd(bcd >> 4)) + digit

def isbcd(bcd):
    """Return True if bcd only contains digits 0-9."""
    try:
        getbcd(bcd)
        return True
    except ValueError:
        return False

class FieldInfo:
    """Information about a field, extracted from the VBI data."""

    def __init__(self, fieldjson):
        # The data values we're extracting
        self.status = None
        self.disctype = None
        self.minutes = None
        self.seconds = None
        self.frames = None
        self.picno = None
        self.stopcode = None
        self.chapter = None

        self.parse_fm(fieldjson)
        self.parse_vbi(fieldjson)

    def __str__(self):
        bits = [
            self.status,
            self.disctype,
            str(self.minutes) + "m" if (self.minutes is not None) else None,
            str(self.seconds) + "s" if (self.seconds is not None) else None,
            str(self.frames) + "f" if (self.frames is not None) else None,
            self.picno,
            "stop" if (self.stopcode is not None) else None,
            "ch" + str(self.chapter) if (self.chapter is not None) else None,
            ]
        return " ".join([str(bit) for bit in bits if bit is not None])

    def parse_fm(self, fieldjson):
        """Extract data from the FM code."""

        ntsc = fieldjson.get("ntsc")
        if ntsc is None:
            return
        if not ntsc.get("isFmCodeDataValid", False):
            return
        fm_data = ntsc.get("fmCodeData")
        if fm_data is None:
            return

        # ld-process-vbi returns just the 20 data bits, in their original
        # order, so we need to reverse them
        value = 0
        for i in range(20):
            value |= ((fm_data >> i) & 1) << (19 - i)

        if (value & 0xF) == 0xA:
            # Lead in
            self.status = "leadin"
        elif (value & 0xF) == 0xC:
            # Lead out
            self.status = "leadout"
        elif (value & 0xF) in (0xB, 0xD) and isbcd(value & 0xFFFF0):
            # CLV mins/secs (0xB for the first 100 frames of the disc)
            self.status = "picture"
            self.disctype = "clv"
            self.minutes = getbcd((value >> 12) & 0xFF)
            self.seconds = getbcd((value >> 4) & 0xFF)
        elif isbcd(value):
            # CAV picture number
            self.status = "picture"
            self.disctype = "cav"
            self.picno = getbcd(value)
        else:
            #print("unknown FM", hex(value))
            pass

    def parse_vbi(self, fieldjson):
        """Extract data from the biphase code."""

        vbi = fieldjson.get("vbi")
        if vbi is None:
            return
        vbi_data = vbi.get("vbiData")
        if vbi_data is None:
            return

        for value in vbi_data:
            if value == 0:
                # No code
                pass
            elif value == 0x88FFFF:
                # Lead in
                self.status = "leadin"
            elif value == 0x80EEEE:
                # Lead out
                self.status = "leadout"
            elif value == 0x82CFFF:
                # Stop code (stop on the *previous* field)
                self.stopcode = True
            elif value == 0x87FFFF:
                # CLV
                self.disctype = "clv"
            elif (value & 0xF0FF00) == 0xF0DD00 and isbcd(value & 0x0F00FF):
                # CLV hours/mins
                self.status = "picture"
                self.disctype = "clv"
                self.minutes = (60 * getbcd((value >> 16) & 0xF)) + getbcd(value & 0x0000FF)
            elif (value & 0xF0F000) == 0x80E000 and ((value >> 16) & 0xF) >= 0xA and isbcd(value & 0x000FFF):
                # CLV sec/frame
                self.status = "picture"
                self.disctype = "clv"
                self.seconds = (10 * (((value >> 16) & 0xF) - 0xA)) + getbcd((value >> 8) & 0xF)
                self.frames = getbcd(value & 0xFF)
            elif (value & 0xF00000) == 0xF00000 and isbcd(value & 0x07FFFF):
                # CAV picture number
                # Top bit duplicates stop code on early discs
                self.status = "picture"
                self.disctype = "cav"
                self.picno = getbcd(value & 0x7FFFF)
            elif (value & 0xF00FFF) == 0x800DDD and isbcd(value & 0x07F000):
                # Chapter number
                # Top bit is 0 for 400 tracks at start of chapter
                self.chapter = getbcd((value >> 12) & 0x7F)
            elif (value & 0xFFF000) in (0x8DC000, 0x8BA000):
                # XXX Programme status code
                # DC = CX on, BA = CX off
                # Other bits indicate audio channel configuration
                pass
            elif (value & 0xF0F000) == 0x80D000:
                # XXX User code in lead in/out
                pass
            else:
                #print("unknown VBI", hex(value))
                pass

def show_vbi(tbcjson):
    """Show the decoded VBI."""

    for index, fieldjson in enumerate(tbcjson["fields"]):
        fi = FieldInfo(fieldjson)
        print(index, fi)

def ffmpeg_escape(s):
    """Escape strings for ffmpeg metadata files."""
    return re.sub(r'[=;#\\\n]', lambda m: "\\" + m.group(0), s)

def make_metadata(tbcjson, metadata_fn):
    """Generate an ffmpeg metadata file with the chapter locations.

    Format description: <https://ffmpeg.org/ffmpeg-formats.html#Metadata-1>"""

    # We'll give positions using field indexes directly, rather than using the
    # times encoded in the VBI, because we might be working with a capture
    # of only part of a disc. Select the appropriate timebase to make this work.
    if tbcjson["videoParameters"]["isSourcePal"]:
        timebase = "1/50"
    else:
        timebase = "1001/60000"

    # Scan through the VBI...
    chapter_changes = []
    stopcodes = set()
    chapter = None
    first_field_index = 0
    for index, fieldjson in enumerate(tbcjson["fields"]):
        # Codes may be in either field; we want the index of the first
        if fieldjson["isFirstField"]:
            first_field_index = index

        fi = FieldInfo(fieldjson)

        if fi.chapter is not None and fi.chapter != chapter:
            # Chapter change
            chapter = fi.chapter
            chapter_changes.append((first_field_index, chapter))

        if fi.stopcode:
            # Stop code
            stopcodes.add(first_field_index)

    # Add a dummy change at the end of the input, so we can get the length of the last chapter
    chapter_changes.append((len(tbcjson["fields"]), None))

    # XXX Discard suspiciously short chapters?

    # Begin the file
    if metadata_fn == "-":
        f = sys.stdout
    else:
        f = open(metadata_fn, "w")
    f.write(";FFMETADATA1\n")

    # Write out the chapters
    for i, change in enumerate(chapter_changes[:-1]):
        f.write("\n")
        f.write("[CHAPTER]\n")
        f.write("TIMEBASE=%s\n" % timebase)
        f.write("START=%d\n" % change[0])
        f.write("END=%d\n" % (chapter_changes[i + 1][0] - 1))
        f.write("title=%s\n" % ffmpeg_escape("Chapter %d" % change[1]))

    # Write out the stop codes
    # XXX Is there a way to represent these properly?
    f.write("\n")
    for index in sorted(stopcodes):
        f.write("; Stop code at %d\n" % index)

    if metadata_fn != "-":
        f.close()

def main():
    # Parse command-line options
    parser = argparse.ArgumentParser()
    parser.add_argument('jsonfile', type=str, help='JSON file containing VBI data')
    parser.add_argument('-m', '--metadata', metavar='FILE', help='Generate ffmpeg metadata file')
    args = parser.parse_args()

    with open(args.jsonfile) as f:
        tbcjson = json.load(f)

    if args.metadata:
        make_metadata(tbcjson, args.metadata)
    else:
        show_vbi(tbcjson)

if __name__ == "__main__":
    main()
