#!/bin/sh
# Create symlinks in a prefix to all the ld-decode tools.

testsuitedir="$(realpath $(dirname $0))"
ldddir="$(realpath $testsuitedir/../ld-decode)"

prefix="$HOME/pkg/ld-decode"

mkdir -p "$prefix/bin" "$prefix/lib"

for f in \
	"$ldddir/tools/shared"/lib*.so* \
	"$ldddir/tools/ld-decode-shared"/lib*.so* \
	; do
	if [ -f "$f" ]; then
		ln -sf "$f" "$prefix/lib/"
	fi
done
for f in \
	"$ldddir/cx" \
	"$ldddir/ld-cut.py" \
	"$ldddir/ld-decode.py" \
	"$ldddir/ld-ldf-reader" \
	"$ldddir/scripts/ld-compress.sh" \
	"$ldddir/tools/ld-analyse/ld-analyse" \
	"$ldddir/tools/ld-chroma-decoder/ld-chroma-decoder" \
	"$ldddir/tools/ld-combine/ld-combine" \
	"$ldddir/tools/ld-discmap/ld-discmap" \
	"$ldddir/tools/ld-dropout-correct/ld-dropout-correct" \
	"$ldddir/tools/ld-lds-converter/ld-lds-converter" \
	"$ldddir/tools/ld-ldstoefm/ld-ldstoefm" \
	"$ldddir/tools/ld-process-efm/ld-process-efm" \
	"$ldddir/tools/ld-process-vbi/ld-process-vbi" \
	; do
	if [ -f "$f" ]; then
		ln -sf "$f" "$prefix/bin/"
	fi
done
