#!/bin/sh
# Create symlinks in a prefix to all the ld-decode tools.

testsuitedir="$(realpath $(dirname $0))"
ldddir="$(realpath $testsuitedir/../ld-decode)"

prefix="$HOME/pkg/ld-decode"

mkdir -p "$prefix/bin"

for f in \
	"$ldddir/cx-expander" \
	"$ldddir/ld-cut" \
	"$ldddir/ld-decode" \
	"$ldddir/ld-ldf-reader" \
	"$ldddir/scripts/ld-compress" \
	"$ldddir/tools/ld-analyse/ld-analyse" \
	"$ldddir/tools/ld-chroma-decoder/encoder/ld-chroma-encoder" \
	"$ldddir/tools/ld-chroma-decoder/ld-chroma-decoder" \
	"$ldddir/tools/ld-diffdod/ld-diffdod" \
	"$ldddir/tools/ld-discmap/ld-discmap" \
	"$ldddir/tools/ld-dropout-correct/ld-dropout-correct" \
	"$ldddir/tools/ld-lds-converter/ld-lds-converter" \
	"$ldddir/tools/ld-ldstoefm/ld-ldstoefm" \
	"$ldddir/tools/ld-process-efm/ld-process-efm" \
	"$ldddir/tools/ld-process-vbi/ld-process-vbi" \
	; do
	if [ -f "$f" ]; then
		ln -sf "$f" "$prefix/bin/"
	fi
done
