#!/usr/bin/python3
# Given an ld-decode .tbc.json file and a picture number, print the (first)
# field number that contains that picture number.
# Usage: picno-to-frame JSON-FILE PIC-NUMBER

import json
import sys

import vbi

with open(sys.argv[1], "r") as f:
    data = json.load(f)
picno = int(sys.argv[2])

for field in data["fields"]:
    info = vbi.FieldInfo(field)
    if info.picno == picno:
        print(((field["seqNo"] - 1) // 2) + 1)
        sys.exit(0)

sys.stderr.write("No frameNumber found matching " + str(picno) + " - has ld-process-vbi been run?\n")
sys.exit(1)
