#!/bin/bash
# Run patched ld-chroma-decoder with a bunch of samples, collecting the stats file.

: \
:

dim=3d
videodir=/d/extra/laserdisc/evaluate-video/video

for mode in composite luma chroma; do
	rm -f binstats

	for rgb in \
		$videodir/lavfi*-625.rgb \
		$videodir/lavfi-pal75bars.rgb \
		$videodir/ldv-*.rgb \
		$videodir/vqeg-*-625.rgb \
		$videodir/svt-*.rgb \
		; do

		base="${rgb%.rgb}"
		if [ "$mode" = "composite" ]; then
			tbc="${base}.tbc"
		else
			tbc="${base}.${mode}.tbc"
		fi

		echo "Decoding $tbc for $mode"
		ld-chroma-decoder -f transform$dim "$tbc" /dev/null

	done

	mv binstats binstats${dim}-all625-$mode
done
