#!/bin/bash
# Run patched ld-chroma-decoder with a bunch of samples, collecting the stats file.

: \
:

videodir=/d/extra/laserdisc/evaluate-video/video

for mode in luma chroma; do
	rm -f binstats

	for rgb in \
		$videodir/lavfi*-625.rgb \
		$videodir/lavfi-pal75bars.rgb \
		$videodir/ldv-*.rgb \
		$videodir/vqeg-*-625.rgb \
		; do

		base="${rgb%.rgb}"
		tbc="${base}.${mode}.tbc"

		echo "Decoding $tbc for $mode"
		ld-chroma-decoder -f transform2d "$tbc" /dev/null

	done

	mv binstats binstats-all625-$mode
done
