#!/bin/sh -ex

ldsdir=/n/stuff2/capture/laserdisc
capdir=/mnt/capture/laserdisc
outdir=/d/extra/laserdisc/audio

if false; then
# PAL analogue, badly cloud-rotted (noisy but few dropouts)
dd if=$ldsdir/MontyPython2x11-13set2_CLV_PAL_side1_4400_2019-10-11_14-57-27.lds of=rotted.lds bs=32000000 skip=600 count=10
ld-lds-converter <rotted.lds | sox -t raw -b 16 -c 1 -e signed -r 4000000 - rotted.wav stats
fi

# ld-ldf-reader FILENAME FIRST-SAMPLE
rate=40000000
start=$(expr 10 \* 60 \* $rate)
length=$(expr 30 \* $rate \* 2)

if false; then
# PAL, C1 error rate 6%
ld-ldf-reader $ldsdir/FawltyTowersS2_CAV_PAL_side1_4400_2019-10-11_22-38-55.raw.oga $start | head -c $length >$outdir/fawlty.s16

# PAL, C1 error rate 15%
ld-ldf-reader $ldsdir/MessageToLove_CLV_PAL_side2_4400_2019-08-25_17-51-18.raw.oga $start | head -c $length >$outdir/wight.s16

# PAL, C1 error rate 24%
ld-ldf-reader $ldsdir/THX1138_CLV_PAL_side1_4400_2019-10-11_18-33-45.raw.oga $start | head -c $length >$outdir/thx.s16

# PAL, ??
ld-ldf-reader $ldsdir/Simon/"Domesday Community_CAV_PAL_side1_North DS1_2019-06-14_15-27-26.raw.oga" $start | head -c $length >$outdir/domesday.s16

# NTSC, C1 error rate 7%
ld-ldf-reader $ldsdir/WarGames_CLV_NTSC_side2_4400_2019-10-04_17-34-28.raw.oga $start | head -c $length >$outdir/wargames.s16

# NTSC, C1 error rate 27%
ld-ldf-reader $ldsdir/TheGratefulDeadMovie_CLV_NTSC_side3_4400_2019-09-17_13-03-32.raw.oga $start | head -c $length >$outdir/grateful.s16

# NTSC, C1 error rate 40%
ld-ldf-reader $ldsdir/ThisIsSpinalTap_CLV_NTSC_side1_4400_2019-09-17_19-04-03.raw.oga $start | head -c $length >$outdir/spinaltap.s16

# NTSC, C1 error rate 99%
ld-ldf-reader $ldsdir/Squibnocket_CLV_NTSC_side2_4400_2019-10-02_22-13-34.raw.oga $start | head -c $length >$outdir/squibnocket.s16
fi

# Samples at varying locations
for loc in 01 02 03 04 05 09 13 20 30 40 50 55; do
	start=$(expr $loc \* 60 \* $rate)
	length=$(expr 10 \* $rate \* 2)

	if false; then
	ld-ldf-reader $ldsdir/ThisIsSpinalTap_CLV_NTSC_side1_4400_2019-09-17_19-04-03.raw.oga $start | head -c $length >$outdir/spinaltap${loc}.s16
	ld-ldf-reader $ldsdir/Squibnocket_CLV_NTSC_side2_4400_2019-10-02_22-13-34.raw.oga $start | head -c $length >$outdir/squibnocket${loc}.s16
	fi

	ld-ldf-reader $capdir/TheCommitments_CLV_PAL_side1_4400d_EE1077_2023-02-26_13-17-58.ldf $start | head -c $length >$outdir/commitmentsA${loc}.s16
	ld-ldf-reader $capdir/TheCommitments_CLV_PAL_side2_4400d_EE1077_2023-02-26_14-21-00.ldf $start | head -c $length >$outdir/commitmentsB${loc}.s16
	ld-ldf-reader $capdir/MacrossPlus1_CLV_NTSC_side1_4400d_BELL-704_2023-01-20_12-27-04.ldf $start | head -c $length >$outdir/macrossA${loc}.s16
	ld-ldf-reader $capdir/MacrossPlus2_CLV_NTSC_side1_4400d_BELL-705_2023-01-20_11-41-23.ldf $start | head -c $length >$outdir/macrossB${loc}.s16
	ld-ldf-reader $capdir/MacrossPlus3_CLV_NTSC_side1_4400d_BELL-706_2023-01-20_13-26-58.ldf $start | head -c $length >$outdir/macrossC${loc}.s16
	ld-ldf-reader $capdir/MacrossPlus4_CLV_NTSC_side1_4400d_BELL-707_2023-01-20_14-15-48.ldf $start | head -c $length >$outdir/macrossD${loc}.s16
	ld-ldf-reader $capdir/TopGun_CLV_PAL_side1_4400d_PLFEB-33631_2023-01-18_22-25-17.ldf $start | head -c $length >$outdir/topgunA${loc}.s16
	ld-ldf-reader $capdir/TopGun_CLV_PAL_side2_4400d_PLFEB-33631_2023-01-18_23-24-22.ldf $start | head -c $length >$outdir/topgunB${loc}.s16
done
